"""
modules/custom_imputer.py — GitHub-based custom imputer support for TIDI.

Workflow:
  1. clone_repo()    — git clone into an isolated tmp directory
  2. inspect_repo()  — scan for requirements.txt and impute-like functions/classes
  3. make_template() — generate a tidi_adapter.py the user edits in-browser
  4. install_deps()  — pip install the repo's requirements
  5. run_adapter()   — execute the adapter in a subprocess (crash-safe)
"""
import os
import re
import ast
import sys
import json
import shutil
import hashlib
import tempfile
import subprocess
from pathlib import Path
from typing import Optional, Tuple, Dict, List

import pandas as pd

_CLONE_ROOT = Path(tempfile.gettempdir()) / "tidi_custom_repos"
_CLONE_ROOT.mkdir(exist_ok=True)


def _repo_dir(url: str) -> Path:
    slug = hashlib.md5(url.strip().encode()).hexdigest()[:12]
    name = url.rstrip("/").split("/")[-1].replace(".git", "")
    return _CLONE_ROOT / f"{name}_{slug}"


# ── Step 1: Clone ─────────────────────────────────────────────────────────────

def clone_repo(url: str, force: bool = False) -> Tuple[bool, str, Path]:
    dest = _repo_dir(url)
    if dest.exists() and not force:
        return True, f"Already cloned at {dest}", dest
    if dest.exists():
        shutil.rmtree(dest, ignore_errors=True)
    if shutil.which("git") is None:
        return False, "git is not installed or not on PATH.", dest
    result = subprocess.run(
        ["git", "clone", "--depth", "1", url, str(dest)],
        capture_output=True, text=True, timeout=120,
    )
    if result.returncode != 0:
        return False, f"git clone failed:\n{result.stderr.strip()}", dest
    return True, f"Cloned successfully to {dest}", dest


# ── Step 2: Inspect ───────────────────────────────────────────────────────────

def inspect_repo(repo_path: Path) -> Dict:
    IMPUTE_KEYWORDS = {"impute", "fill", "transform", "fit_transform", "complete", "infer"}
    info: Dict = {
        "requirements": [], "has_setup": False, "has_pyproject": False,
        "py_files": [], "functions": [], "classes": [],
        "readme_snippet": "", "package_name": repo_path.name,
    }

    req_path = repo_path / "requirements.txt"
    if req_path.exists():
        info["requirements"] = [
            l.strip() for l in req_path.read_text().splitlines()
            if l.strip() and not l.startswith("#")
        ]
    info["has_setup"]     = (repo_path / "setup.py").exists()
    info["has_pyproject"] = (repo_path / "pyproject.toml").exists()

    for rname in ["README.md", "README.rst", "README.txt", "readme.md"]:
        rp = repo_path / rname
        if rp.exists():
            info["readme_snippet"] = rp.read_text(errors="ignore")[:600]
            break

    for py_file in list(repo_path.glob("*.py")) + list(repo_path.glob("*/*.py")):
        rel = str(py_file.relative_to(repo_path))
        info["py_files"].append(rel)
        try:
            tree = ast.parse(py_file.read_text(errors="ignore"))
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):
                if any(kw in node.name.lower() for kw in IMPUTE_KEYWORDS):
                    info["functions"].append({
                        "file": rel, "name": node.name,
                        "args": [a.arg for a in node.args.args],
                    })
            if isinstance(node, ast.ClassDef):
                methods = [
                    {"name": item.name, "args": [a.arg for a in item.args.args]}
                    for item in node.body
                    if isinstance(item, ast.FunctionDef)
                    and any(kw in item.name.lower() for kw in IMPUTE_KEYWORDS)
                ]
                if methods:
                    info["classes"].append(
                        {"file": rel, "class": node.name, "methods": methods}
                    )
    return info


# ── Step 3: Generate adapter template ────────────────────────────────────────

_ADAPTER_HEADER = '''\
"""
tidi_adapter.py — Auto-generated by TIDI.
Edit the impute() function to match the repo\'s API, then click Run.

Contract:
  impute(df: pd.DataFrame, cols: list) -> pd.DataFrame
"""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "repo"))

import pandas as pd
import numpy as np
'''


def make_template(info: Dict, repo_path: Path) -> str:
    pkg   = info.get("package_name", "mypackage")
    lines = [_ADAPTER_HEADER, ""]

    if info["classes"]:
        cls   = info["classes"][0]
        meth  = cls["methods"][0]["name"]
        cname = cls["class"]
        fname = cls["file"].replace("/", ".").replace(".py", "")
        lines += [
            f"# Detected: class {cname}.{meth}() in {cls['file']}",
            f"from {fname} import {cname}", "",
            "def impute(df: pd.DataFrame, cols: list) -> pd.DataFrame:",
            f"    imputer = {cname}()",
            "    numeric_cols = [c for c in cols if pd.api.types.is_numeric_dtype(df[c])]",
            "    cat_cols     = [c for c in cols if c not in numeric_cols]",
            "    result = df.copy()",
            "    if numeric_cols:",
            f"        filled = imputer.{meth}(df[numeric_cols])",
            "        result[numeric_cols] = filled.values if hasattr(filled, 'values') else filled",
            "    for c in cat_cols:",
            "        result[c] = result[c].fillna(result[c].mode().iloc[0] if not result[c].mode().empty else 'unknown')",
            "    return result",
        ]
    elif info["functions"]:
        fn    = info["functions"][0]
        fname = fn["file"].replace(".py", "").replace("/", ".")
        lines += [
            f"# Detected: function {fn['name']}() in {fn['file']}",
            f"from {fname} import {fn['name']}", "",
            "def impute(df: pd.DataFrame, cols: list) -> pd.DataFrame:",
            "    result = df.copy()",
            f"    result = {fn['name']}(result)  # adjust arguments as needed",
            "    return result",
        ]
    else:
        lines += [
            f"# No impute-like function detected. Fill in manually.",
            f"# Example: from {pkg} import SomeClass", "",
            "def impute(df: pd.DataFrame, cols: list) -> pd.DataFrame:",
            "    result = df.copy()",
            "    # ── YOUR CODE HERE ──────────────────────────────────────",
            "    return result",
        ]
    return "\n".join(lines)


# ── Step 4: Install dependencies ─────────────────────────────────────────────

def install_deps(repo_path: Path) -> Tuple[bool, str]:
    logs = []

    def _run(cmd):
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
        logs.append(f"$ {' '.join(cmd)}\n{r.stdout}\n{r.stderr}".strip())
        return r.returncode == 0

    if (repo_path / "setup.py").exists() or (repo_path / "pyproject.toml").exists():
        _run([sys.executable, "-m", "pip", "install",
              "--break-system-packages", "-e", str(repo_path), "--quiet"])

    req = repo_path / "requirements.txt"
    if req.exists():
        ok = _run([sys.executable, "-m", "pip", "install",
                   "--break-system-packages", "-r", str(req), "--quiet"])
        if not ok:
            return False, "\n".join(logs)

    return True, "\n".join(logs)


# ── Step 5: Run adapter in subprocess ────────────────────────────────────────

_RUNNER_SCRIPT = '''\
import sys, json
import pandas as pd

adapter_path, input_csv, output_csv, cols_json = sys.argv[1:5]
cols = json.loads(cols_json)
df   = pd.read_csv(input_csv).replace("__TIDI_NA__", float("nan"))

import importlib.util
spec = importlib.util.spec_from_file_location("tidi_adapter", adapter_path)
mod  = importlib.util.module_from_spec(spec)
spec.loader.exec_module(mod)

result = mod.impute(df.copy(), cols)
assert isinstance(result, pd.DataFrame), "impute() must return a DataFrame"
assert result.shape == df.shape, f"Shape mismatch: {result.shape} vs {df.shape}"
result.to_csv(output_csv, index=False)
print("__TIDI_OK__")
'''


def run_adapter(adapter_code: str, df: pd.DataFrame, cols: list,
                repo_path: Path, timeout: int = 300,
                ) -> Tuple[Optional[pd.DataFrame], Optional[pd.DataFrame], str]:
    with tempfile.TemporaryDirectory() as tmp:
        tmp = Path(tmp)
        adapter_path = tmp / "tidi_adapter.py"
        adapter_path.write_text(
            f"import sys, os\nsys.path.insert(0, {repr(str(repo_path))})\n" + adapter_code
        )
        runner_path = tmp / "_runner.py"
        runner_path.write_text(_RUNNER_SCRIPT)
        input_csv  = tmp / "input.csv"
        output_csv = tmp / "output.csv"
        df.copy().fillna("__TIDI_NA__").to_csv(input_csv, index=False)

        result = subprocess.run(
            [sys.executable, str(runner_path),
             str(adapter_path), str(input_csv), str(output_csv), json.dumps(cols)],
            capture_output=True, text=True, timeout=timeout,
        )
        log = (result.stdout + "\n" + result.stderr).strip()

        if result.returncode != 0 or "__TIDI_OK__" not in result.stdout:
            return None, None, f"Adapter failed (exit {result.returncode}):\n{log}"
        if not output_csv.exists():
            return None, None, "Adapter ran but produced no output CSV."

        imputed = pd.read_csv(output_csv)
        for c in df.columns:
            if c in imputed.columns:
                try:
                    imputed[c] = imputed[c].astype(df[c].dtype)
                except Exception:
                    pass

        return imputed, df.isna() & imputed.notna(), log
